SPECTATOR_WINDOW_BG = '#33313B'
SPECTATORS_TIMER_COLOR = "white"
CONTROL_GENERAL_BG='#A09DA5'

ATHLETE_1_COLOR = '#CC443E'
ATHLETE_2_COLOR = '#2A4EB9'

SET_BUTTON_1 = '1.TButton'
SET_BUTTON_2 = '2.TButton'

ENTRY_STYLE_1 = '1.TEntry'
ENTRY_STYLE_2 = '2.TEntry'

LABEL_STYLE_1 = 'label_1.TLabel'
LABEL_STYLE_2 = 'label_2.TLabel'

FALL_LABEL_STYLE = 'label_3.TLabel'
FALL_POINTS_STYLE = 'label_4.TLabel'

SPECTATORS_THEME_DARK = 'label_5.TLabel'

SPECTATORS_TIMER_THEME = 'label_6.TLabel'
